"""initial schema

Revision ID: db1a7b55b4f3
Revises: 
Create Date: 2026-02-20 03:10:35.657236

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db1a7b55b4f3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('plan', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('endpoints',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('response_code', sa.Integer(), nullable=False),
    sa.Column('response_body', sa.String(length=10000), nullable=False),
    sa.Column('response_content_type', sa.String(length=100), nullable=False),
    sa.Column('request_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_endpoints_user_id'), 'endpoints', ['user_id'], unique=False)
    op.create_table('forwarding_configs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('endpoint_id', sa.String(length=36), nullable=False),
    sa.Column('target_url', sa.String(length=2048), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('timeout_seconds', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['endpoint_id'], ['endpoints.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_forwarding_configs_endpoint_id'), 'forwarding_configs', ['endpoint_id'], unique=True)
    op.create_table('webhook_requests',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('endpoint_id', sa.String(length=36), nullable=False),
    sa.Column('method', sa.String(length=10), nullable=False),
    sa.Column('headers', sa.Text(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('query_params', sa.Text(), nullable=False),
    sa.Column('content_type', sa.String(length=255), nullable=False),
    sa.Column('source_ip', sa.String(length=45), nullable=False),
    sa.Column('body_size', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['endpoint_id'], ['endpoints.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_webhook_requests_created_at'), 'webhook_requests', ['created_at'], unique=False)
    op.create_index(op.f('ix_webhook_requests_endpoint_id'), 'webhook_requests', ['endpoint_id'], unique=False)
    op.create_table('forwarding_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('forwarding_config_id', sa.String(length=36), nullable=False),
    sa.Column('webhook_request_id', sa.String(length=36), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('response_time_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['forwarding_config_id'], ['forwarding_configs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['webhook_request_id'], ['webhook_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_forwarding_logs_forwarding_config_id'), 'forwarding_logs', ['forwarding_config_id'], unique=False)
    op.create_index(op.f('ix_forwarding_logs_webhook_request_id'), 'forwarding_logs', ['webhook_request_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_forwarding_logs_webhook_request_id'), table_name='forwarding_logs')
    op.drop_index(op.f('ix_forwarding_logs_forwarding_config_id'), table_name='forwarding_logs')
    op.drop_table('forwarding_logs')
    op.drop_index(op.f('ix_webhook_requests_endpoint_id'), table_name='webhook_requests')
    op.drop_index(op.f('ix_webhook_requests_created_at'), table_name='webhook_requests')
    op.drop_table('webhook_requests')
    op.drop_index(op.f('ix_forwarding_configs_endpoint_id'), table_name='forwarding_configs')
    op.drop_table('forwarding_configs')
    op.drop_index(op.f('ix_endpoints_user_id'), table_name='endpoints')
    op.drop_table('endpoints')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
